### ISSUE TITLE
[L5.5] Plugin doesn't generate images

### ISSUE THREAD

**Issue by vojtasvoboda** [mplodowski/dynamicpdf-plugin#42]
Hi Renatio,

I'm having trouble with images inside PDF. When I'm trying this code in template:

```
{% set config = {mode: 'crop', extension: 'auto'} %}
<img src="{{ user.avatar.getThumb(260, 260, config) }}" alt="" />
```

it gets me this PDF:

![snimek obrazovky 2017-07-28 v 16 10 53](https://user-images.githubusercontent.com/374917/28721078-62cc5c2c-73af-11e7-8f2a-d318879a8b86.png)

I have tried to debug template output by this snippet:

```
$pdf = App::make('dynamicpdf');
$user = UserModel::find(1);
$template = Template::byCode('rainlab::user');
dd($pdf->parseTemplate($template, compact('user')));
```

And it returns correct code with correct image path:

![snimek obrazovky 2017-07-28 v 16 07 20](https://user-images.githubusercontent.com/374917/28721089-7535f01c-73af-11e7-92ad-b15bedd456c2.png)

This code definitely works in previous versions, because I'm using it at [User PDF export](https://octobercms.com/plugin/vojtasvoboda-userexportpdf) plugin and I also make some screenshots for plugin page, where user avatars are shown.

Do you know, where could be a problem please? Tried on latest October build 419 with Laravel 5.5.

Thank you very much!
Vojta

**Comment by mplodowski** [comment]
Hi,

please update plugin to allow Laravel 5.5 - https://github.com/mplodowski/DynamicPDF/commit/40259f5c78dfcd2e5166ea22c7f7ee3dfda3a282

In your code template change:

    <img src="{{ user.avatar.getThumb(260, 260, config) | slice(1) }}" alt="" />

to

    <img src="{{ user.avatar.getThumb(260, 260, config) }}" alt="" />

In your example there is no `slice` function, but when I installed your plugin it was there.

In `plugins/vojtasvoboda/userexportpdf/behaviors/PdfExportBehavior.php:30` add following option:

    'isRemoteEnabled' => true

I tested this and it worked with Laravel 5.5.

**Comment by vojtasvoboda** [comment]
Hi Michal,

sorry for late reply. All changes were done: https://github.com/vojtasvoboda/oc-userexportpdf-plugin/commit/2d48be91559c3d98690292594e4852cc5915d96b

But the user avatar is still hidden + generate PDF takes about 2 minutes.

Could you please test it?

Thanks
Vojta

**Comment by mplodowski** [comment]
After I pulled your changes everything works fine. I have pdf with embedded avatar.

[michal-michalplodowski-at-gmailcom.pdf](https://github.com/mplodowski/dynamicpdf-plugin/files/1285976/michal-michalplodowski-at-gmailcom.pdf)

For `isRemoteEnabled` option to work, you must have this php settings enabled: `allow_url_fopen=1`.

Another approach will be to generate full path relative links.

Example: 

```
/home/vagrant/code/october/storage/app/uploads/public/59b/1a1/e87/59b1a1e879d93974530641.jpeg
```

This can be done with getLocalPath() function on avatar like so `{{ user.avatar.getLocalPath() }}`.

I cannot find function to generate local path for thumbs. Probably you will have to make it on your own.
